services:
  app:
    build: .
    image: whitenoise-caster
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.prod.yaml:/app/config.yaml:ro
      - ./whitenoise.mp3:/app/whitenoise.mp3:ro
