// Minimal CastMessage definition from Chromium's cast_channel.proto.
// Only includes what we need — no AuthChallenge/AuthResponse/DeviceAuthMessage.
// Must use proto2 to match the wire format Chromecast devices expect
// (required fields and zero-valued enums must be serialized).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: cast/proto/v1/cast_channel.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CastMessage_ProtocolVersion int32

const (
	CastMessage_CASTV2_1_0 CastMessage_ProtocolVersion = 0
)

// Enum value maps for CastMessage_ProtocolVersion.
var (
	CastMessage_ProtocolVersion_name = map[int32]string{
		0: "CASTV2_1_0",
	}
	CastMessage_ProtocolVersion_value = map[string]int32{
		"CASTV2_1_0": 0,
	}
)

func (x CastMessage_ProtocolVersion) Enum() *CastMessage_ProtocolVersion {
	p := new(CastMessage_ProtocolVersion)
	*p = x
	return p
}

func (x CastMessage_ProtocolVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CastMessage_ProtocolVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_cast_proto_v1_cast_channel_proto_enumTypes[0].Descriptor()
}

func (CastMessage_ProtocolVersion) Type() protoreflect.EnumType {
	return &file_cast_proto_v1_cast_channel_proto_enumTypes[0]
}

func (x CastMessage_ProtocolVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CastMessage_ProtocolVersion) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CastMessage_ProtocolVersion(num)
	return nil
}

// Deprecated: Use CastMessage_ProtocolVersion.Descriptor instead.
func (CastMessage_ProtocolVersion) EnumDescriptor() ([]byte, []int) {
	return file_cast_proto_v1_cast_channel_proto_rawDescGZIP(), []int{0, 0}
}

type CastMessage_PayloadType int32

const (
	CastMessage_STRING CastMessage_PayloadType = 0
	CastMessage_BINARY CastMessage_PayloadType = 1
)

// Enum value maps for CastMessage_PayloadType.
var (
	CastMessage_PayloadType_name = map[int32]string{
		0: "STRING",
		1: "BINARY",
	}
	CastMessage_PayloadType_value = map[string]int32{
		"STRING": 0,
		"BINARY": 1,
	}
)

func (x CastMessage_PayloadType) Enum() *CastMessage_PayloadType {
	p := new(CastMessage_PayloadType)
	*p = x
	return p
}

func (x CastMessage_PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CastMessage_PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_cast_proto_v1_cast_channel_proto_enumTypes[1].Descriptor()
}

func (CastMessage_PayloadType) Type() protoreflect.EnumType {
	return &file_cast_proto_v1_cast_channel_proto_enumTypes[1]
}

func (x CastMessage_PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CastMessage_PayloadType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CastMessage_PayloadType(num)
	return nil
}

// Deprecated: Use CastMessage_PayloadType.Descriptor instead.
func (CastMessage_PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_cast_proto_v1_cast_channel_proto_rawDescGZIP(), []int{0, 1}
}

type CastMessage struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	ProtocolVersion *CastMessage_ProtocolVersion `protobuf:"varint,1,req,name=protocol_version,json=protocolVersion,enum=cast.proto.v1.CastMessage_ProtocolVersion" json:"protocol_version,omitempty"`
	SourceId        *string                      `protobuf:"bytes,2,req,name=source_id,json=sourceId" json:"source_id,omitempty"`
	DestinationId   *string                      `protobuf:"bytes,3,req,name=destination_id,json=destinationId" json:"destination_id,omitempty"`
	Namespace       *string                      `protobuf:"bytes,4,req,name=namespace" json:"namespace,omitempty"`
	PayloadType     *CastMessage_PayloadType     `protobuf:"varint,5,req,name=payload_type,json=payloadType,enum=cast.proto.v1.CastMessage_PayloadType" json:"payload_type,omitempty"`
	PayloadUtf8     *string                      `protobuf:"bytes,6,opt,name=payload_utf8,json=payloadUtf8" json:"payload_utf8,omitempty"`
	PayloadBinary   []byte                       `protobuf:"bytes,7,opt,name=payload_binary,json=payloadBinary" json:"payload_binary,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CastMessage) Reset() {
	*x = CastMessage{}
	mi := &file_cast_proto_v1_cast_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastMessage) ProtoMessage() {}

func (x *CastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cast_proto_v1_cast_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastMessage.ProtoReflect.Descriptor instead.
func (*CastMessage) Descriptor() ([]byte, []int) {
	return file_cast_proto_v1_cast_channel_proto_rawDescGZIP(), []int{0}
}

func (x *CastMessage) GetProtocolVersion() CastMessage_ProtocolVersion {
	if x != nil && x.ProtocolVersion != nil {
		return *x.ProtocolVersion
	}
	return CastMessage_CASTV2_1_0
}

func (x *CastMessage) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *CastMessage) GetDestinationId() string {
	if x != nil && x.DestinationId != nil {
		return *x.DestinationId
	}
	return ""
}

func (x *CastMessage) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *CastMessage) GetPayloadType() CastMessage_PayloadType {
	if x != nil && x.PayloadType != nil {
		return *x.PayloadType
	}
	return CastMessage_STRING
}

func (x *CastMessage) GetPayloadUtf8() string {
	if x != nil && x.PayloadUtf8 != nil {
		return *x.PayloadUtf8
	}
	return ""
}

func (x *CastMessage) GetPayloadBinary() []byte {
	if x != nil {
		return x.PayloadBinary
	}
	return nil
}

var File_cast_proto_v1_cast_channel_proto protoreflect.FileDescriptor

const file_cast_proto_v1_cast_channel_proto_rawDesc = "" +
	"\n" +
	" cast/proto/v1/cast_channel.proto\x12\rcast.proto.v1\"\xa5\x03\n" +
	"\vCastMessage\x12U\n" +
	"\x10protocol_version\x18\x01 \x02(\x0e2*.cast.proto.v1.CastMessage.ProtocolVersionR\x0fprotocolVersion\x12\x1b\n" +
	"\tsource_id\x18\x02 \x02(\tR\bsourceId\x12%\n" +
	"\x0edestination_id\x18\x03 \x02(\tR\rdestinationId\x12\x1c\n" +
	"\tnamespace\x18\x04 \x02(\tR\tnamespace\x12I\n" +
	"\fpayload_type\x18\x05 \x02(\x0e2&.cast.proto.v1.CastMessage.PayloadTypeR\vpayloadType\x12!\n" +
	"\fpayload_utf8\x18\x06 \x01(\tR\vpayloadUtf8\x12%\n" +
	"\x0epayload_binary\x18\a \x01(\fR\rpayloadBinary\"!\n" +
	"\x0fProtocolVersion\x12\x0e\n" +
	"\n" +
	"CASTV2_1_0\x10\x00\"%\n" +
	"\vPayloadType\x12\n" +
	"\n" +
	"\x06STRING\x10\x00\x12\n" +
	"\n" +
	"\x06BINARY\x10\x01B8Z6github.com/telnesstech/whitenoise-caster/cast/proto/v1"

var (
	file_cast_proto_v1_cast_channel_proto_rawDescOnce sync.Once
	file_cast_proto_v1_cast_channel_proto_rawDescData []byte
)

func file_cast_proto_v1_cast_channel_proto_rawDescGZIP() []byte {
	file_cast_proto_v1_cast_channel_proto_rawDescOnce.Do(func() {
		file_cast_proto_v1_cast_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cast_proto_v1_cast_channel_proto_rawDesc), len(file_cast_proto_v1_cast_channel_proto_rawDesc)))
	})
	return file_cast_proto_v1_cast_channel_proto_rawDescData
}

var file_cast_proto_v1_cast_channel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cast_proto_v1_cast_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cast_proto_v1_cast_channel_proto_goTypes = []any{
	(CastMessage_ProtocolVersion)(0), // 0: cast.proto.v1.CastMessage.ProtocolVersion
	(CastMessage_PayloadType)(0),     // 1: cast.proto.v1.CastMessage.PayloadType
	(*CastMessage)(nil),              // 2: cast.proto.v1.CastMessage
}
var file_cast_proto_v1_cast_channel_proto_depIdxs = []int32{
	0, // 0: cast.proto.v1.CastMessage.protocol_version:type_name -> cast.proto.v1.CastMessage.ProtocolVersion
	1, // 1: cast.proto.v1.CastMessage.payload_type:type_name -> cast.proto.v1.CastMessage.PayloadType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cast_proto_v1_cast_channel_proto_init() }
func file_cast_proto_v1_cast_channel_proto_init() {
	if File_cast_proto_v1_cast_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cast_proto_v1_cast_channel_proto_rawDesc), len(file_cast_proto_v1_cast_channel_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cast_proto_v1_cast_channel_proto_goTypes,
		DependencyIndexes: file_cast_proto_v1_cast_channel_proto_depIdxs,
		EnumInfos:         file_cast_proto_v1_cast_channel_proto_enumTypes,
		MessageInfos:      file_cast_proto_v1_cast_channel_proto_msgTypes,
	}.Build()
	File_cast_proto_v1_cast_channel_proto = out.File
	file_cast_proto_v1_cast_channel_proto_goTypes = nil
	file_cast_proto_v1_cast_channel_proto_depIdxs = nil
}
